admin_dashboard:
    path: /
    controller: App\Controller\Admin\DashboardController::showAdminDashboard
    methods: ['GET']

admin_news_create:
    path: /news
    controller: App\Controller\Admin\NewsCrudController::create
    methods: ['POST']

admin_news_list:
    path: /news
    controller: App\Controller\Admin\NewsCrudController::list
    methods: ['GET']

admin_news_creat_form:
    path: /news/creatForm
    controller: App\Controller\Admin\NewsCrudController::createForm
    methods: ['GET']

admin_news_show:
    path: /news/{id}
    controller: App\Controller\Admin\NewsCrudController::show
    methods: ['GET']

admin_news_delete:
    path: /news/{id}delete
    controller: App\Controller\Admin\NewsCrudController::delete
    methods: ['DELETE', 'POST']

admin_news_edit_form:
    path: /news/{id}/editForm
    controller: App\Controller\Admin\NewsCrudController::createEditForm
    methods: ['GET']

admin_news_edit:
    path: /news/{id}edit
    controller: App\Controller\Admin\NewsCrudController::edit
    methods: ['PUT', 'PATCH', 'POST']

admin_comment_create:
    path: /comment/{id}/create
    controller: App\Controller\Admin\CommentCrudController::create
    methods: ['POST']

admin_comment_delete:
    path: /comment/{id}/delete
    controller: App\Controller\Admin\CommentCrudController::delete
    methods: ['DELETE', 'POST']

admin_comment_create_form:
    path: /comment/{id}/editForm
    controller: App\Controller\Admin\CommentCrudController::createEditForm
    methods: ['GET']

admin_comment_edit:
    path: /comment/{id}/edit
    controller: App\Controller\Admin\CommentCrudController::edit
    methods: ['PUT', 'PATCH', 'POST']
